//Need to follow alphabetical order with below mentioned notation
export const ABOUT = "About";
export const ABOUT_CORPORATION_LINK = "/about-the-coperation";
export const ABOUT_EVENTS_LINK = "/about-events-and-awards";
export const ABOUT_HOSPITAL = "About Hospital";
export const ABOUT_IT_LINK = "/about-it-initiative";
export const ABOUT_LEADERSHIP_LINK = "/about-tgsrtc-leadership";
export const ABOUT_LINK = "/about-vision-legacy";
export const ABOUT_LOGISTICS = "About Logistics";
export const ABOUT_LOGISTICS_PARA_1 = "Telangana State Road Transport Corporation (TGSRTC) is a State Transport Undertaking which provides Public Transport. It has a fleet of about 9,700 buses. TGSRTC launched Cargo and Parcel Services in June, 2020 for transporting Cargo and Parcels in its buses. The services are provided at all TGSRTC Bus Stations located across the State and to neighbouring States at identified important locations where counters are provided. Parcel & Cargo Agents have been identified for this purpose and they provide services from their counters.";
export const ABOUT_LOGISTICS_PARA_2_CONTENT = "for contact details of Counters/Agents. Home delivery facility is available in Hyderabad City."
export const ABOUT_LOGISTICS_PARA_2 = " The consignors can approach the nearest bus station or counter and book their consignment for delivery at their desired location. The consignment will be transported through TGSRTC buses and delivered to the Bus Station/Counter at the destination as desired by the customer. The consignee has to collect the consignment from the Bus Station/Counter. Please visit"
export const ABOUT_TGSRTC_PARAGRAPH = " Since its inception in 2014, Telangana State Road Transport Corporation (TGSRTC) TGSRTC has remained committed to excellence in bus transport. Our focus on safety, environmental sustainability, and top-notch service ensures passenger satisfaction and industry leadership."
export const ABOUT_TGSRTC_TITLE = "About TGSRTC";
export const AIRPORT_PUSHPAK_FIRST_PARAGRAPH = "Pushpak is a special AC service provided by TGSRTCUntil now it is known as a special service only to the airport, but Pushpak airport liner buses are not exclusive buses to the airport - they pick up and drop commuters at many locations in the city. If you search for ‘Pushpak airport liner near me’ in a search engine, you may find a few stops near you where you can board Pushpak buses and get down at any Pushpak bus stop or even go to the airport. Because it goes till the airport it is called the airport bus shuttle. So, if you search ‘airport bus stop near me’, you will get the details of Pushpak bus stops near your location."
export const AIRPORT_PUSHPAK_SECOND_PARAGRAPH = "Pushpak bus timings are very convenient as it is a round-the-clock-service. If you cannot find the schedule or the details online, you can dial the Pushpak airport bus contact number and seek information regarding Pushpak bus booking and timings. You can avail the tickets directly in the bus. Pushpak is the only AC service in Hyderabad and it is safe, secure and fast. Pushpak not only goes to the airport, but to many other destinations in Hyderabad."
export const ANNEXURE = "ANNEXURE: A";
export const APPLE_PLAY_STORE_URL = "https://apps.apple.com/us/app/tsrtc/id1201934852?ls=1";
export const APPLY_AND_RENEW = "Apply, Renew & Travel effortlessly with TGSRTC";
export const APPLY_NOW = "Apply Now";
export const BANGALORE = "Bangalore";
export const BHADRACHALAM = "Bhadrachalam";
export const BOOK_APPOINTMENT = "Book Appointment";
export const BOOK_NOW = "Book Now";
export const BOOK_YOUR_CARGO = "Book Your Cargo";
export const BOOK_YOUR_SERVICE = "Book Your Services";
export const BOOK_YOUR_SERVICE_PARAGRAPH = "Telangana State Road Transport Corporation (TGSRTC) boasts a fleet of over 10,000 buses, serving major routes within Telangana andacross states like Andhra Pradesh, Karnataka, Tamil Nadu, and Maharashtra. With operations spanning 36,593 routes in India, TSRTC is dedicated to offering top-notch facilities, punctual services, and affordable ticket prices for a safe and comfortable journey. Secure your TSRTC online booking today!";
export const BOOK_YOUR_TICKET_PARAGRAPH = "Conveniently book tickets online for a hassle free travel experience";
export const BOOK_YOUR_TICKET = "Book Your Ticket";
export const BOOK_YOUR_TRAVEL_TICKET = "Apply, Renew & Travel effortlessly with TGSRTC";
export const BUS_CONTRACT_RATES = "Bus on Contract Rates";
export const BUS_CONTRACT_RATES_TAGLINE = "TGSRTC is happy to announce the following package tours to our valuable commuters at affordable rates.";
export const BUS_DETAILS = "Bus Details";
export const BUS_PASS_FAQ_LINK = "/bus-passes-faq";
export const BUS_PASS_GENERAL_LINK = "/bus-pass-general-commuter-pass";
export const BUS_PASS_LINK = "/bus-pass-services";
export const BUS_PASS_OPTIONS = "Bus Pass Options";
export const BUS_PASS_OTHER_LINK = "/other-passes";
export const BUS_PASS_SERVICES = "Bus Pass Services";
export const BUS_PASS_STUDENT_LINK = "/bus-pass-student-passes";
export const BUS_PASSES = "Bus Passes";
export const BUS_PASSES_PARAGRAPH = "Dedicated to delivering top-notch services through teamwork, aiming for passenger satisfaction and a leading position in the transport sector. Additionally, TSRTC offers a range of bus passes to cater to various passenger needs. ";
export const CAREERS = "Careers";
export const CAREERS_LINK = "/careers";
export const CHENNAI = "Chennai";
export const CITY_SERVICES = "City Services";
export const CONCESSION_SCHEMES = "Concession Schemes";
export const CONTACT_US = "Contact us";
export const CONTACT_US_LINK = "/contact-us";
export const CORPORATION = "The Corporation";
export const DATE = "14-05-2024";
export const DATE_LABEL = "Date";
export const DELIVERS_EXCELLENCE = "Delivers excellence every mile !";
export const DESTINATION = "Destinations";
export const DETAILS_OF_AIRPORT_PUSHPAK_BUSES = "Details of Airport Pushpak bus timings"
export const DETAILS_OF_HYDERABAD_BUSES = "Details of Hyderabad bus timings"
export const DETAILS_OF_MUNCHINTALA_BUSES = "Details of Muchintala bus timings"
export const DETAILS_OF_RESERVATION_POINTS = "Details of Reservation Points"
export const DETAILS_RESERVATION_POINTS = "Details of Reservation Points"
export const DOWNLOAD_OUR_APP = "Download our app";
export const Electric_BUSES_PARA = " The following facilities are available in Electric Buses and specially operated to RGI Airport."
export const Electric_BUSES = "Electric Buses";
export const EMAIL_PLACEHOLDER = "Enter your email here...";
export const EMAIL_TYPE = "email";
export const EMAIL = "Email";
export const EVENTS_AWARDS = "Events & Awards";
export const FACEBOOK_URL = "https://www.facebook.com/search/top?q=tsrtcmdoffice";
export const FACILITY = "Facility for Long Distance Passengers";
export const FAQ = "FAQ";
export const FAQ_HEADING = "Frequently Asked Questions";
export const FAQ_SUBTITLE = "Apply, Renew & Travel effortlessly with TGSRTC";
export const FAQS = "FAQ's";
export const FEEDBACK = "Feedback";
export const FEEDBACK_LINK = "/feedback";
export const FEEDBACK_PLACEHOLDER = "Enter your Feedback/Suggestions here..."
export const FEEDBACK_TITLE = "Please Give your Feedback/Suggestions";
export const FOLLOW_US = "Follow us on @TGSRTCMDOFFICE";
export const FROM_LABEL = "From";
export const GAMAYAM_APP = "Gamyam App";
export const GAMAYAM_APP_PARAGRAPH = "Experience seamless travel with TGSRTC's innovative TGSRTC Gamyam mobile app, offering real-time tracking for all buses. With this convenient feature, passengers can effortlessly monitor the status of all bus services, ensuring a smooth and stress-free journey";
export const GARUDA_PLUS_HEADING = "Garuda Plus (Multi Axle A.C)";
export const GARUDA_PLUS_PARA = "The Corporation has earmarked seats in buses for ladies, physically challenged, MLAs/MPs, Senior Citizens, Presidents of Mandal Parishads & ZPTC members etc. The layout diagrams of each type of bus are shown here.";
export const GENERAL_COMMUTER_PASS = "General Commuter Pass";
export const GENERAL_PASS = "General Commuter Pass";
export const GOOGLE_PLAY_STORE_URL = "https://play.google.com/store/apps/details?id=com.app.tsrtc";
export const GUIDING_PRINCIPLE = "Guiding Principles of TGSRTC";
export const HERO_TITLE = "TGSRTC serving people since 1932";
export const HIRE_BUS = "Hire Bus";
export const HIRE_BUS_PARAGRAPH = "TGSRTC offers bus rental services for weddings, events, and special occasions at competitive rates. Opt for their chartered service for a safe and enjoyable journey.";
export const HOME = "Home";
export const HOSPITAL_LINK = "/tarnaka-hospital";
export const HOSPITAL_STANDS = "Tarnaka Hospital stands out for its commitment to providing essential healthcare services to the community. With a focus on efficient diagnosis, treatment, and care, TGSRTC Tarnaka Hospital serves as a vital resource for affordable and reliable medical assistance. TGSRTC Hospital started in the year 1978 as a 40 bedded Hospital, now is a 200 bedded Super Specialty Hospital spread across 7.7 acres of lush green landscape at Tarnaka, Hyderabad catering 1200+ outpatients per day.";
export const HYDERABAD = "Hyderabad";
export const HYDERABAD_FIRST_PARAGRAPH = "After more than five years of renovation and reconstruction, Telangana’s Yadadri (Yadagirigutta) temple has transformed from a small hill shrine into a magnificent and sprawling pilgrimage centre. To help pilgrims reach the shrine, TGSRTC has started special buses that go to Yadadri. Now you have 104 buses from Hyderabad to Yadadri (Yadagirigutta). JBS to Yadagirigutta bus timings and MGBS to Yadagirigutta bus timings are set up in such a way that there are ample options for pilgrims to choose from."
export const HYDERABAD_LABEL = "Hyderabad (HYD)";
export const HYDERABAD_SECOND_PARAGRAPH = "Located about 60 km from Hyderabad, it has undergone a complete transformation in line with Chief Minister K. Chandrasekhar Rao’s ambitious vision. To realize his vision, Yadagirigutta bus timings and also Yadagirigutta ticket price are carefully planned so as to provide citizens with cheap, safe and secure travelling service. Be it JBS to Yadagirigutta bus ticket price or MGBS to Yadagirigutta ticket price, TGSRTC is determined to provide cost-effective, pocket-friendly and the best service."
export const HYDERABAD_THIRD_PARAGRAPH = "Choose TGSRTC Make Hyderabad to Yadadri journey safe, secure and simple"
export const INDIA_GOVT_URL = "https://www.india.gov.in/";
export const INFORMATION = "Information";
export const INSTAGRAM_URL = "https://www.instagram.com/tsrtcmdoffice/?utm_medium=copy_link";
export const INTERCITY = "Intercity";
export const INTRACITY = "Intracity";
export const IT_INITIATIVES = "IT Initiatives";
export const KARIMNAGAR = "Karimnagar";
export const KNOW_MORE = "Know more about";
export const KNOW_MORE_ABOUT_FAQ = "Know more about FAQ'S";
export const KNOW_MORE_ABOUT_GENERAL_PASSES = "Know more about General passes";
export const KNOW_MORE_ABOUT_OTHER_PASSES = "Know more about Other passes";
export const KNOW_MORE_ABOUT_STUDENT_PASSES = "Know more about student passes";
export const KNOW_MORE_LABEL = "Know more";
export const KPI_NUMBER1 = "10";
export const KPI_NUMBER1_LABEL = "Buses Running";
export const KPI_NUMBER1_METRICS = "K";
export const KPI_NUMBER2 = "3.8";
export const KPI_NUMBER2_LABEL = "On Avg. Daily Bus Bookings";
export const KPI_NUMBER2_METRICS = "M";
export const KPI_NUMBER3 = "40";
export const KPI_NUMBER3_LABEL = "Transporting Passengers";
export const KPI_NUMBER3_METRICS = "L";
export const LABEL1 = "For reckoning the waiting time, an average running time @30 Kms per hour will be calculated for non-AC buses and @40 Kms per hour for A/C buses for the actual distance and the balance period will be treated as waiting time rounded off to next half hour.";
export const LABEL2 = "After 16 Hours, hire charges for 16 Hrs Plus @15KMs per Hour & Rate per KM";
export const LADIES = "Ladies";
export const LEADERSHIP = "TGSRTC Leadership";
export const LOGISTICS = "Logistics";
export const LOGISTICS_CONTACTS = "Contacts";
export const LOGISTICS_CONTACTS_LINK = "/logistic-contacts";
export const LOGISTICS_FAQ = "FAQ";
export const LOGISTICS_LINK = "/logistics-tgsrtc-home";
export const LOGISTICS_RATES_LINK = "/logistic-rates-and-tariffs-contacts";
export const LOOKING_TO_SEND_PACKAGE = " Looking for send your package ?";
export const MENU = "Menu";
export const METRO_DELUX_COACH_PARA = "Metro Deluxe Coaches with better features like attractive colour scheme, seat comfort, wider windows etc., are introduced in place of Metro liners for the benefit of long distance city commuters.";
export const METRO_DELUX_COACH = "Metro Deluxe coach for twin cities of Hyderabad and Secunderabad";
export const METRO_DELUX = "Metro Deluxe";
export const METRO_EXPRESS = "Metro Express";
export const METRO_LUXURY_AC = "Metro Luxury A.C";
export const MLA = "MLAs/MPs";
export const MONTHLY_SEASON_TCIKETS_HEADING = "Monthly Season Tickets: (MST)";
export const MUNCHINTALA_FIRST_PARAGRAPH = "Muchintala village in Ranga Reddy district is now an international destination. Taking forward Sri Ramanuja’s ideals and philosophy, Sri Chinna Jeeyar Swamy has dreamt of a larger-than-life statue, the statue of equality, and a vast campus of worship for pilgrims. To help people reach the destination, TGSRTC has arranged special buses to the statue of equality and has prepared a schedule for statue of equality bus timings."
export const MUNCHINTALA_SECOND_PARAGRAPH = "Muchintala bus timings are convenient and available. Now, the journey to Muchintala is easy and simple with TGSRTCFor TGSRTC buses to Muchintala refer to the below schedule. Have a safe and secure journey with TGSRTC"
export const NAME_PLACEHOLDER = "Enter your name here...";
export const NAME = "Name";
export const NEWS_UPDATES = "News & Updates";
export const NEWS_UPDATES_CARD_CONTENT = "Lorem ipsum dolor sit amet, adipiscing elit. sed do eiusmod temporincididunt ut. adipiscing elit. sed do eiusmod tempor incididunt ut.";
export const NEWS_UPDATES_CARD_TITLE = "International Women's Day";
export const NON_TGSRTC_EMPLOYEE = "+91-9154298817 - Non TGSRTC Employee";
export const OTHER_BUS_PASSES = "Other Bus Passes";
export const OTHER_BUS_PASSES_PARA = "The following facilities are specially operated in cities.";
export const OTHER_CITY_BUSES = "Other City Buses";
export const OTHER_PASSES = "Other Passes";
export const PACKAGE_TOUR_WILL = "Package tour will be starting from alpha hotel sec-bad @08:30am and take you to birla mandir, golkonda fort, taramati baradari,where you can have lunch {at your own cost} chowmahala palace, charminar, lumbini park & back to alpha hotel.";
export const PHONE_NO = "Phone No.";
export const PHONE_NUMBER_PLACEHOLDER = "Enter your phone number here...";
export const PHYSICALLY_CHALLENGED = "Physically challenged";
export const PLACES_COVERED = "Places covered & description";
export const PRESIDENTS_MANDAL = "Presidents of Mandal/ZPTCs of Mandals";
export const PRIVACY_POLICIES = "Privacy Policies";
export const PRIVACY_POLICIES_LINK = "/privacy-policy";
export const PUSHPAK_AIRPORT_LINERS = "Pushpak Airport Liner bus point controllers and contact numbers"
export const QUICKLINKS = "Quick Links";
export const RAJDHANI_HEADING = "Rajadhani A / C Buses";
export const RAJDHANI_PARA = "To provide a comfortable A C buses at affordable fare, TGSRTC introduced 12 m A/C buses under brand name 'Rajadhani' with an intermediary fare between Super Luxury and Garuda plus.";
export const RATES_TABLE1_TITLE = "Pickup and Drop upto 200 kms contract (One way)";
export const RATES_TABLE2_TITLE = "Bus on Contract (200 Kms Minimum)(District Services)";
export const RATES_TABLE3_TITLE = "Hire Charges for City Services (City Ordinary, Metro Express & Metro Deluxe services)(SLAB RATES)";
export const RECOGNITION_URL = "https://www.asrtu.org/";
export const RESERVATION_FAQ = "Reservations FAQ";
export const RESERVATION_LABEL = "Reservations";
export const RESERVATION_POINTS = "Reservations Points";
export const RESERVATION_POINTS1 = "Reservation Points";
export const RESERVATIONS = "Reservations";
export const RESERVATIONS_BUS_LINK = "/reservation-bus-details";
export const RESERVATIONS_CONCESSION_LINK = "/reservation-concession-schemes";
export const RESERVATIONS_CONTRACT_LINK = "/reservation-contract-rates";
export const RESERVATIONS_FAQ_LINK = "/reservation-faq";
export const RESERVATIONS_LINK = "/reservation-booking-service-home";
export const RESERVATIONS_POINTS_LINK = "/reservation-points";
export const RESERVATIONS_SPL_BUS_LINK = "/reservation-special-bus-timing";
export const RESERVATIONS_TOURISM_LINK = "/reservation-tourism";
export const ROAD_SAFETY = "Road Safety";
export const ROAD_SAFETY_LINK = "/road-safety";
export const ROUND_TRIP = "I want to book a round trip";
export const ROUTES_TEXT = " Routes you may be interested in";
export const RT_CONTACTS = "Rates and Tariffs Contacts";
export const RTI_ACT = "RTI Act, 2005";
export const RTI_ACT_LINK = "/rti-act";
export const SALIENT_FEATURES = "The Salient Features";
export const SAMPLE_STRING = "Sample string";
export const SEARCH_BUSSES = "Search Buses";
export const SEAT_LAYOUT_OF_TGSRTC = "Seat-Layout of TGSRTC";
export const SEAT_LAYOUT_OF_TGSRTC_PARA = "The Corporation has ear marked seats in buses for ladies, physically challenged, MLAs/MPs, Senior Citizens, Presidents of Mandal Parishads & ZPTC members etc. The layout diagrams of each type of bus are shown here."
export const SEND_A_PARCEL = "Send A Parcel";
export const SENIOR_CITIZENS = "Senior citizens";
export const SHIRIDI = "Shiridi";
export const SITE_MAP = "Site Map";
export const SITE_MAP_LINK = "/site-map";
export const SPECIAL_BUS_TIMINGS = "Special Bus Timings";
export const SPECIAL_BUSES = "Special Bus Timings"
export const SRISAILAM = "Srisailam";
export const STUDENT_PASSES = "Student Passes";
export const SUBMIT_TYPE = "submit";
export const SUGGESTIONS = "Feedback / Suggestion";
export const SUPER_LUXURY_HEADING = "Super Luxury";
export const SUPER_LUXURY_PARA = "The following facilities are available in Super Luxury Coaches:";
export const T20_TICKET = " T-24 ticket can be purchased at any time from any city bus conductor and is valid for next 24 hrs from the date and time of purchase of the ticket"
export const TARIFFS = "Tariffs of monthly season tickets:";
export const TARNAKA_HOSPITAL_TAGLINE = "Your Gateway to Quality Health Care";
export const TARNAKA_HOSPITAL = "TGSRTC Tarnaka Hospital";
export const TELEGRAM_URL = "https://t.me/tsrtcmdoffice";
export const TELEPHONE_TYPE = "tel";
export const TENDERS = "Tenders";
export const TENDERS_LINK = "/tenders";
export const TERMS_AND_CONDITIONS = "Terms & Condition";
export const TEXT_TYPE = "text";
export const TGSRTC = "TGSRTC";
export const TGSRTC_AIRPORT = "TGSRTC Airport Pushpak bus timings - Towards RGIA"
export const TGSRTC_COPYRIGHT = " Copyright © 2021 TGSRTC, All Rights Reserved.";
export const TGSRTC_EMPLOYEE = "+91-9154298785 - For TGSRTC Employee";
export const TGSRTC_HOSPITAL = "TGSRTC Hospital";
export const TGSRTC_HOSPITAL_EMAIL = "support@TSRTChospital.com";
export const TGSRTC_HOSPITAL_PARAGRAPH = "TGSRTC Tarnaka Hospital stands out for its commitment to providing essential healthcare services to the community. With a focus on efficient diagnosis, treatment, and care, TSRTC Tarnaka Hospital serves as a vital resource for affordable and reliable medical assistance.";
export const TGSRTC_LINK_NAME = " www.TGSRTC.telangana.gov.in";
export const TGSRTC_LINK = "https://www.tsrtc.telangana.gov.in/";
export const TGSRTC_LOGISTICS = "TGSRTC Logistics";
export const TGSRTC_LOGISTICS_BUSINESS = "TGSRTC Logistics Business";
export const TGSRTC_LOGISTICS_BUSINESS_PARA_1 = "TGSRTC As transportation of bulk goods demand has grown significantly in the state, we have moved towards Logistics sector bulk luggage through our separate Cargo Transport closed Vehicles which can carry up to 10 tones. We also transport Parcels and deliver at the quickest With Effect From 19.06.2020 services with 150 cargo bus were operated through private the task of freight management pricing.";
export const TGSRTC_LOGISTICS_BUSINESS_PARA_2 = " CARGO TRANSPORTVEHICLE TGSRTC LOGISTICS BUSINESS As transportation of bulk goods demand has grown significantly in the towards Logistics sector also with a view to transport bulk luggage through our separate Cargo Transport closed Vehicles which can and Courier the goods within and outside possible time. 19.06.2020 TGSRTC has introduced Parcel bus services. Earlier, the cargo and parcel were operated through private agencies. However, TGSRTC has now management under its brand with a highly As transportation of bulk goods demand has grown significantly in the view to transport bulk luggage through our separate Cargo Transport closed Vehicles which can outside the state and Cargo parcel services However, TGSRTC has now taken up competitive";
export const TGSRTC_LOGISTICS_PARAGRAPH = "TGSRTC introduced Cargo and Parcel Services in June 2020, offering transportation of goods across the state and neighboring areas. With designated counters at key locations and appointed agents, consignors can conveniently book their shipments at any TGSRTC bus station, ensuring efficient delivery to their desired destinations for collection by the consignee.";
export const TGSRTC_MIYAPUR = "TGSRTC Miyapur -2 Depot Pushpak Service Operations"
export const TIRUPATI = "Tirupati";
export const TO_ATTRACT_MORE = "To attract more long distance (250 Kms and more) passengers, free journey facility is extended on the strength of advance reservation ticket by city and district buses to the bus station (Journey origin point) and from bus station to in the peripheral areas. This facility is valid 2 Hrs before commencement of journey (to reach Bus Station) and 2 Hrs after arriving at the destination (to reach their dwelling place) where City Buses are under operation. i.e., Hyderabad & Warangal."
export const TO_LABEL = "To";
export const TODAY_LABEL = "Today";
export const TOMMAROW_LABEL = "Tomorrow";
export const TOURISM = "Tourism";
export const TOURISM_OFFER_LINE = "TGSRTC is happy to announce the following package tours to our valuable commuters at affordable rates.";
export const TOURISM_PICKUP = "Pickup - Alpha Hotel Secundarabad";
export const TOURISM_QUOTE1 = '"Life is short and the world is wide"';
export const TOURISM_QUOTE2 = '"Travel is the investment in yourself"';
export const TOURISM_TIME = "08:30 am to 08:00 pm (Weekends)";
export const TRAVEL_24HOURS = `"Travel-24(T-24)" tickets were introduced from 15.09.2016 with unlimited travel within the twin cities of Hyderabad/Secunderabad for 24 hrs. Tariff of Non AC ticket is priced at Rs.100/- by which passenger can travel in all types of city buses (except AC) within city limits and AC Travel-24 is priced at Rs.160/- to travel in all types of city buses including AC buses within city limits.`;
export const TRAVEL_ACROSS_TG = "Travel across Telangana on our TGSRTC buses and explore tourist places.";
export const TRAVEL_EFFORTLESSLY = "Apply, Renew & Travel effortlessly with TGSRTC";
export const TRAVEL = "Travel-24(T-24) Tickets";
export const TWITTER_URL = "https://x.com/i/flow/login?redirect_after_login=%2Fsearch%3Fq%3Dtsrtcmdoffice";
export const TYPES_OF_COACHES = "Types of Coaches of TGSRTC";
export const VALUE_ADDITION = "Value addition given to MST holders";
export const VIEW_ALL_ROUTES = "View all Routes";
export const VIEW_DETAILS = "View Details";
export const VIEW_MORE = "View More";
export const VIJAYAWADA = "Vijayawada";
export const VISAKHAPATNAM_LABEL = "Visakhapatnam (VSPK)";
export const WARANGAL_LABEL = "Warangal (WL)"
export const WE_ARE_AVAILABLE = "We Are Available For You !";
export const WHAT_SERVICE_HEADING = "What Service We Provide";
export const WHICH_BUS_TIMINGS = "Which bus timings do you want to view?"
