//Need to follow alphabetical order with below mentioned notation
export const  ABOUT_LOGISTICS_PARA_2=" The consignors can approach the nearest bus station or counter and book their consignment for delivery at their desired location. The consignment will be transported through TGSRTC buses and delivered to the Bus Station/Counter at the destination as desired by the customer. The consignee has to collect the consignment from the Bus Station/Counter. Please visit"
export const ABOUT = "About";
export const ABOUT_HOSPITAL="About Hospital";
export const ABOUT_LOGISTICS = "About Logistics";
export const ABOUT_LOGISTICS_PARA_1="Telangana State Road Transport Corporation (TGSRTC) is a State Transport Undertaking which provides Public Transport. It has a fleet of about 9,700 buses. TGSRTC launched Cargo and Parcel Services in June, 2020 for transporting Cargo and Parcels in its buses. The services are provided at all TGSRTC Bus Stations located across the State and to neighbouring States at identified important locations where counters are provided. Parcel & Cargo Agents have been identified for this purpose and they provide services from their counters.";
export const ABOUT_LOGISTICS_PARA_2_CONTENT="for contact details of Counters/Agents. Home delivery facility is available in Hyderabad City."
export const ABOUT_US = "About Us";
export const AIRPORT_PUSHPAK_FIRST_PARAGRAPH="Pushpak is a special AC service provided by TGSRTCUntil now it is known as a special service only to the airport, but Pushpak airport liner buses are not exclusive buses to the airport - they pick up and drop commuters at many locations in the city. If you search for ‘Pushpak airport liner near me’ in a search engine, you may find a few stops near you where you can board Pushpak buses and get down at any Pushpak bus stop or even go to the airport. Because it goes till the airport it is called the airport bus shuttle. So, if you search ‘airport bus stop near me’, you will get the details of Pushpak bus stops near your location."
export const AIRPORT_PUSHPAK_SECOND_PARAGRAPH="Pushpak bus timings are very convenient as it is a round-the-clock-service. If you cannot find the schedule or the details online, you can dial the Pushpak airport bus contact number and seek information regarding Pushpak bus booking and timings. You can avail the tickets directly in the bus. Pushpak is the only AC service in Hyderabad and it is safe, secure and fast. Pushpak not only goes to the airport, but to many other destinations in Hyderabad."
export const APPLE_PLAY_STORE_URL ="https://apps.apple.com/us/app/tsrtc/id1201934852?ls=1";
export const APPLY_AND_RENEW = "Apply, Renew & Travel effortlessly with TSRTC";
export const APPLY_NOW = "Apply Now";
export const BOOK_APPOINTMENT="Book Appointment";
export const BOOK_YOUR_CARGO="Book Your Cargo";
export const BUS_CONTRACT_RATES = "Bus on Contract Rates";
export const BUS_DETAILS = "Bus Details";
export const BUS_PASS_OPTIONS = "Bus pass Options";
export const BUS_PASS_SERVICES = "Bus Pass Services";
export const BUS_PASSES = "Bus Passes";
export const CAREERS = "Careers";
export const CONCESSION_SCHEMES = "Concession Schemes";
export const CONTACT_US = "Contact us";
export const CORPORATION = "The Corporation";
export const DELIVERS_EXCELLENCE="Delivers excellence every mile !";
export const DETAILS_OF_AIRPORT_PUSHPAK_BUSES="Details of Airport Pushpak bus timings"
export const DETAILS_OF_HYDERABAD_BUSES="Details of Hyderabad bus timings"
export const DETAILS_OF_MUNCHINTALA_BUSES="Details of Muchintala bus timings"
export const DOWNLOAD_OUR_APP = "Download our app";
export const EVENTS_AWARDS = "Events & Awards";
export const FACEBOOK_URL ="https://www.facebook.com/search/top?q=tsrtcmdoffice";
export const FAQS = "FAQ's";
export const FEEDBACK = "Feedback";
export const FOLLOW_US = "Follow us on @TGSRTCMDOFFICE";
export const GENERAL_COMMUTER_PASS = "General Commuter Pass";
export const GENERAL_PASS = "General Commuter Pass";
export const GOOGLE_PLAY_STORE_URL ="https://play.google.com/store/apps/details?id=com.app.tsrtc";
export const HOME = "Home";
export const HOSPITAL_STANDS="Tarnaka Hospital stands out for its commitment to providing essential healthcare services to the community. With a focus on efficient diagnosis, treatment, and care, TGSRTC Tarnaka Hospital serves as a vital resource for affordable and reliable medical assistance. TGSRTC Hospital started in the year 1978 as a 40 bedded Hospital, now is a 200 bedded Super Specialty Hospital spread across 7.7 acres of lush green landscape at Tarnaka, Hyderabad catering 1200+ outpatients per day.";
export const HYDERABAD_FIRST_PARAGRAPH="After more than five years of renovation and reconstruction, Telangana’s Yadadri (Yadagirigutta) temple has transformed from a small hill shrine into a magnificent and sprawling pilgrimage centre. To help pilgrims reach the shrine, TGSRTC has started special buses that go to Yadadri. Now you have 104 buses from Hyderabad to Yadadri (Yadagirigutta). JBS to Yadagirigutta bus timings and MGBS to Yadagirigutta bus timings are set up in such a way that there are ample options for pilgrims to choose from."
export const HYDERABAD_SECOND_PARAGRAPH="Located about 60 km from Hyderabad, it has undergone a complete transformation in line with Chief Minister K. Chandrasekhar Rao’s ambitious vision. To realize his vision, Yadagirigutta bus timings and also Yadagirigutta ticket price are carefully planned so as to provide citizens with cheap, safe and secure travelling service. Be it JBS to Yadagirigutta bus ticket price or MGBS to Yadagirigutta ticket price, TGSRTC is determined to provide cost-effective, pocket-friendly and the best service."
export const HYDERABAD_THIRD_PARAGRAPH="Choose TGSRTC Make Hyderabad to Yadadri journey safe, secure and simple"
export const INDIA_GOVT_URL = "https://www.india.gov.in/";
export const INFORMATION = "Information";
export const INSTAGRAM_URL ="https://www.instagram.com/tsrtcmdoffice/?utm_medium=copy_link";
export const IT_INITIATIVES = "IT Initiatives";
export const KNOW_MORE = "Know more about";
export const KNOW_MORE_ABOUT_FAQ = "Know more about FAQ'S";
export const KNOW_MORE_ABOUT_GENERAL_PASSES = "Know more about General passes";
export const KNOW_MORE_ABOUT_OTHER_PASSES = "Know more about Other passes";
export const KNOW_MORE_ABOUT_STUDENT_PASSES = "Know more about student passes";
export const LEADERSHIP = "TGSRTC Leadership";
export const LOGISTICS = "Logistics";
export const LOGISTICS_CONTACTS = "Contacts";
export const LOGISTICS_FAQ = "FAQ";
export const LOOKING_TO_SEND_PACKAGE=" Looking for send your package ?";
export const MUNCHINTALA_FIRST_PARAGRAPH="Muchintala village in Ranga Reddy district is now an international destination. Taking forward Sri Ramanuja’s ideals and philosophy, Sri Chinna Jeeyar Swamy has dreamt of a larger-than-life statue, the statue of equality, and a vast campus of worship for pilgrims. To help people reach the destination, TGSRTC has arranged special buses to the statue of equality and has prepared a schedule for statue of equality bus timings."
export const MUNCHINTALA_SECOND_PARAGRAPH="Muchintala bus timings are convenient and available. Now, the journey to Muchintala is easy and simple with TGSRTCFor TGSRTC buses to Muchintala refer to the below schedule. Have a safe and secure journey with TGSRTC"
export const NON_TGSRTC_EMPLOYEE = "+91-9154298817 - Non TGSRTC Employee";
export const OTHER_BUS_PASSES = "Other Bus Passes";
export const OTHER_PASSES = "Other Passes";
export const PRIVACY_POLICIES = "Privacy Policies";
export const PUSHPAK_AIRPORT_LINERS="Pushpak Airport Liner bus point controllers and contact numbers"
export const QUICKLINKS = "Quicklinks";
export const RECOGNITION_URL = "https://www.asrtu.org/";
export const RESERVATION_FAQ = "Reservations FAQ";
export const RESERVATION_LABEL = "Reservations";
export const RESERVATION_POINTS = "Reservations Points";
export const RESERVATIONS = "Reservations";
export const ROAD_SAFETY = "Road Safety";
export const RT_CONTACTS = "Rates and Tariffs Contacts";
export const RTI_ACT = "RTI Act, 2005";
export const SAMPLE_STRING = "Sample string";
export const SEND_A_PARCEL="Send A Parcel";
export const SITE_MAP = "Site Map";
export const SPECIAL_BUS_TIMINGS = "Special Bus Timings";
export const SPECIAL_BUSES="Special Bus Timings"
export const STUDENT_PASSES = "Student Passes";
export const TARNAKA_HOSPITAL_TAGLINE="Your Gateway to Quality Health Care";
export const TARNAKA_HOSPITAL="TGSRTC Tarnaka Hospital";
export const TELEGRAM_URL = "https://t.me/tsrtcmdoffice";
export const TENDERS = "Tenders";
export const TGSRTC_AIRPORT="TGSRTC Airport Pushpak bus timings - Towards RGIA"
export const TGSRTC_COPYRIGHT =" Copyright © 2021 TGSRTC, All Rights Reserved.";
export const TGSRTC_EMPLOYEE = "+91-9154298785 - For TGSRTC Employee";
export const TGSRTC_HOSPITAL = "TGSRTC Hospital";
export const TGSRTC_HOSPITAL_EMAIL = "support@TSRTChospital.com";
export const TGSRTC_LINK_NAME=" www.TGSRTC.telangana.gov.in";
export const TGSRTC_LINK="https://www.tsrtc.telangana.gov.in/";
export const TGSRTC_LOGISTICS_BUSINESS = "TGSRTC Logistics Business";
export const TGSRTC_LOGISTICS_BUSINESS_PARA_1="TGSRTC As transportation of bulk goods demand has grown significantly in the state, we have moved towards Logistics sector bulk luggage through our separate Cargo Transport closed Vehicles which can carry up to 10 tones. We also transport Parcels and deliver at the quickest With Effect From 19.06.2020 services with 150 cargo bus were operated through private the task of freight management pricing.";
export const TGSRTC_LOGISTICS_BUSINESS_PARA_2=" CARGO TRANSPORTVEHICLE TGSRTC LOGISTICS BUSINESS As transportation of bulk goods demand has grown significantly in the towards Logistics sector also with a view to transport bulk luggage through our separate Cargo Transport closed Vehicles which can and Courier the goods within and outside possible time. 19.06.2020 TGSRTC has introduced Parcel bus services. Earlier, the cargo and parcel were operated through private agencies. However, TGSRTC has now management under its brand with a highly As transportation of bulk goods demand has grown significantly in the view to transport bulk luggage through our separate Cargo Transport closed Vehicles which can outside the state and Cargo parcel services However, TGSRTC has now taken up competitive";
export const TGSRTC_LOGISTICS="TGSRTC Logistics";
export const TGSRTC_MIYAPUR="TGSRTC Miyapur -2 Depot Pushpak Service Operations"
export const TOURISM = "Tourism";
export const TWITTER_URL ="https://x.com/i/flow/login?redirect_after_login=%2Fsearch%3Fq%3Dtsrtcmdoffice";
export const VIEW_DETAILS = "View Details";
export const VIEW_MORE = "View More";
export const WE_ARE_AVAILABLE = "We Are Available For You !";
export const WHAT_SERVICE_HEADING="What Service We Provide";
export const WHICH_BUS_TIMINGS="Which bus timings do you want to view?"