export const yadagiriguttaTableData = [
    {
      sNo: "#",
      serviceType: "Service Type",
      fromStage: "Hyderabad",
      fromTime: "From Time",
      toStage: "Yadagirigutta",
      toTime: "To Time",
    },
    {
      sNo: 1,
      serviceType: "Pallevelugu",
      fromStage: "Hyderabad",
      fromTime: "07:20",
      toStage: "Yadagirigutta",
      toTime: "07:00",
    },
    {
      sNo: 2,
      serviceType: "Pallevelugu",
      fromStage: "Hyderabad",
      fromTime: "07:20",
      toStage: "Yadagirigutta",
      toTime: "07:00",
    },
    {
      sNo: 3,
      serviceType: "Pallevelugu",
      fromStage: "Hyderabad",
      fromTime: "07:20",
      toStage: "Yadagirigutta",
      toTime: "07:00",
    },
    {
      sNo: 4,
      serviceType: "Pallevelugu",
      fromStage: "Hyderabad",
      fromTime: "07:20",
      toStage: "Yadagirigutta",
      toTime: "07:00",
    },
  ];